import type {Skeleton} from './types';

export const sharedHumanoidSkeleton: Skeleton = {
  id: 'humanoid-v1',
  parts: {
    torso: {
      parentPart: null,
      parentJoint: 'root',
      pivot: [95, 235],
      position: [0, -235],
      rotation: 0,
      scale: [1, 1],
      zIndex: 20,
    },
    head: {
      parentPart: 'torso',
      parentJoint: 'neck',
      pivot: [70, 135],
      position: [95, 20],
      rotation: 0,
      scale: [1, 1],
      zIndex: 40,
    },
    upperArmLeft: {
      parentPart: 'torso',
      parentJoint: 'leftShoulder',
      pivot: [30, 20],
      position: [22, 55],
      rotation: 8,
      scale: [1, 1],
      zIndex: 10,
    },
    lowerArmLeft: {
      parentPart: 'upperArmLeft',
      parentJoint: 'leftElbow',
      pivot: [30, 18],
      position: [30, 150],
      rotation: 0,
      scale: [1, 1],
      zIndex: 11,
    },
    upperArmRight: {
      parentPart: 'torso',
      parentJoint: 'rightShoulder',
      pivot: [30, 20],
      position: [168, 55],
      rotation: -8,
      scale: [1, 1],
      zIndex: 30,
    },
    lowerArmRight: {
      parentPart: 'upperArmRight',
      parentJoint: 'rightElbow',
      pivot: [30, 18],
      position: [30, 150],
      rotation: 0,
      scale: [1, 1],
      zIndex: 31,
    },
    upperLegLeft: {
      parentPart: 'torso',
      parentJoint: 'leftHip',
      pivot: [30, 20],
      position: [62, 225],
      rotation: 0,
      scale: [1, 1],
      zIndex: 12,
    },
    lowerLegLeft: {
      parentPart: 'upperLegLeft',
      parentJoint: 'leftKnee',
      pivot: [30, 15],
      position: [30, 162],
      rotation: 0,
      scale: [1, 1],
      zIndex: 13,
    },
    upperLegRight: {
      parentPart: 'torso',
      parentJoint: 'rightHip',
      pivot: [30, 20],
      position: [128, 225],
      rotation: 0,
      scale: [1, 1],
      zIndex: 22,
    },
    lowerLegRight: {
      parentPart: 'upperLegRight',
      parentJoint: 'rightKnee',
      pivot: [30, 15],
      position: [30, 162],
      rotation: 0,
      scale: [1, 1],
      zIndex: 23,
    },
  },
};
